#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void usage(const char *prog)
{
    fprintf(stderr,
            "Usage: %s <output_map> [template_input]\n"
            "\n"
            "Writes lock metadata map in format:\n"
            "  lock_addr_hex,type_name,location\n"
            "\n"
            "If template_input is provided, it copies non-comment lines from input to output.\n",
            prog);
}

int main(int argc, char **argv)
{
    const char *out_path;
    const char *in_path = NULL;
    FILE *out;

    if (argc < 2) {
        usage(argv[0]);
        return 1;
    }

    out_path = argv[1];
    if (argc >= 3)
        in_path = argv[2];

    out = fopen(out_path, "w");
    if (!out) {
        perror("fopen output");
        return 1;
    }

    fprintf(out, "# lock_addr_hex,type_name,location\n");
    fprintf(out, "# generated by extract_lock_info (skeleton mode)\n");

    if (in_path) {
        FILE *in = fopen(in_path, "r");
        char line[512];

        if (!in) {
            perror("fopen input");
            fclose(out);
            return 1;
        }

        while (fgets(line, sizeof(line), in)) {
            if (line[0] == '#')
                continue;
            if (line[0] == '\n' || line[0] == '\r')
                continue;
            fputs(line, out);
        }

        fclose(in);
    }

    fclose(out);
    return 0;
}
